"""empty message

Revision ID: 18110ea8a394
Revises: 4e73c7fae445
Create Date: 2018-04-16 21:40:36.076098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18110ea8a394'
down_revision = '4e73c7fae445'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('jobseekerName', sa.String(length=20), nullable=True),
    sa.Column('jobseekerPhone', sa.String(length=15), nullable=True),
    sa.Column('userExperience', sa.Integer(), nullable=True),
    sa.Column('jobseekerResume', sa.String(length=1024), nullable=True),
    sa.Column('compangHomepage', sa.String(length=1024), nullable=True),
    sa.Column('companyField', sa.String(length=20), nullable=True),
    sa.Column('companyFinancing', sa.String(length=20), nullable=True),
    sa.Column('companyCity', sa.String(length=20), nullable=True),
    sa.Column('companyLogo', sa.String(length=255), nullable=True),
    sa.Column('companyIntroduction', sa.String(length=1024), nullable=True),
    sa.Column('companyDescription', sa.String(length=4096), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userName', sa.String(length=255), nullable=False),
    sa.Column('userEmail', sa.String(length=255), nullable=False),
    sa.Column('userPassword', sa.String(length=256), nullable=False),
    sa.Column('userRole', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('userEmail')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
