"""empty message

Revision ID: 26e544206635
Revises: 
Create Date: 2018-04-21 10:07:18.159915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26e544206635'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag_name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag_name')
    )
    op.create_table('user',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=255), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('userPassword', sa.String(length=256), nullable=False),
    sa.Column('user_role', sa.Integer(), nullable=False),
    sa.Column('user_phone', sa.String(length=15), nullable=True),
    sa.Column('user_experience', sa.Integer(), nullable=True),
    sa.Column('user_resume', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('user_email')
    )
    op.create_table('company',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_homepage', sa.String(length=20), nullable=True),
    sa.Column('company_field', sa.String(length=20), nullable=True),
    sa.Column('company_financing', sa.String(length=20), nullable=True),
    sa.Column('company_city', sa.String(length=20), nullable=True),
    sa.Column('company_logo', sa.String(length=255), nullable=True),
    sa.Column('company_introduction', sa.String(length=1024), nullable=True),
    sa.Column('company_description', sa.String(length=4096), nullable=True),
    sa.Column('company_slug', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('job',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_name', sa.String(length=255), nullable=False),
    sa.Column('job_description', sa.String(length=4096), nullable=False),
    sa.Column('job_address', sa.String(length=1024), nullable=False),
    sa.Column('job_salary_l', sa.Integer(), nullable=False),
    sa.Column('job_salary_h', sa.Integer(), nullable=False),
    sa.Column('job_experience', sa.String(length=255), nullable=False),
    sa.Column('job_education', sa.String(length=255), nullable=False),
    sa.Column('job_company', sa.Integer(), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['job_company'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('delivery',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delivery_job', sa.Integer(), nullable=False),
    sa.Column('delivery_company', sa.Integer(), nullable=False),
    sa.Column('delivery_user', sa.Integer(), nullable=False),
    sa.Column('delivery_status', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['delivery_company'], ['company.id'], ),
    sa.ForeignKeyConstraint(['delivery_job'], ['job.id'], ),
    sa.ForeignKeyConstraint(['delivery_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tags')
    op.drop_table('delivery')
    op.drop_table('job')
    op.drop_table('company')
    op.drop_table('user')
    op.drop_table('tag')
    # ### end Alembic commands ###
