"""empty message

Revision ID: 91136d229d4a
Revises: 
Create Date: 2018-04-20 15:53:03.443690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91136d229d4a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deliveryJob', sa.Integer(), nullable=False),
    sa.Column('deliveryCompany', sa.Integer(), nullable=False),
    sa.Column('deliveryJobseeker', sa.Integer(), nullable=False),
    sa.Column('deliveryStatus', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=255), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('userPassword', sa.String(length=256), nullable=False),
    sa.Column('user_role', sa.Integer(), nullable=False),
    sa.Column('user_phone', sa.String(length=15), nullable=True),
    sa.Column('jobseeker_experience', sa.Integer(), nullable=True),
    sa.Column('jobseeker_resume', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('user_email')
    )
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_homepage', sa.String(length=20), nullable=True),
    sa.Column('company_field', sa.String(length=20), nullable=True),
    sa.Column('company_financing', sa.String(length=20), nullable=True),
    sa.Column('company_city', sa.String(length=20), nullable=True),
    sa.Column('company_logo', sa.String(length=255), nullable=True),
    sa.Column('company_introduction', sa.String(length=1024), nullable=True),
    sa.Column('company_description', sa.String(length=4096), nullable=True),
    sa.Column('company_slug', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('job',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_name', sa.String(length=255), nullable=False),
    sa.Column('job_tag', sa.String(length=255), nullable=False),
    sa.Column('job_description', sa.String(length=4096), nullable=False),
    sa.Column('job_address', sa.String(length=1024), nullable=False),
    sa.Column('job_salary_l', sa.Integer(), nullable=False),
    sa.Column('job_salary_h', sa.Integer(), nullable=False),
    sa.Column('job_experience', sa.String(length=255), nullable=False),
    sa.Column('job_education', sa.String(length=255), nullable=False),
    sa.Column('job_company', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_company'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job')
    op.drop_table('company')
    op.drop_table('user')
    op.drop_table('delivery')
    # ### end Alembic commands ###
